spring:
  datasource:
#    name: test
    url: jdbc:h2:~/test
    username: sa
    password: sa
  h2:
    console:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
    default-executor-type: BATCH